theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
auto-format = false
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[keys.normal]
C-c = "no_op"

[keys.insert]
C-c = "normal_mode"
